# Generated by Django 5.2.16 on 2026-07-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(default='Unknown'),
        ),
    ]
